
CREATE TYPE EQUIPAMENTO_TIPO AS ENUM('Monitor', 'CPU', 'Teclado');
CREATE TYPE EQUIPAMENTO_STATUS AS ENUM('Ativo', 'Manutencao');

CREATE TABLE EQUIPAMENTO(
	ID INT GENERATED ALWAYS AS IDENTITY,
	NOME VARCHAR(150) NOT NULL,
	TIPO EQUIPAMENTO_TIPO NOT NULL,
	DATA_AQUISICAO DATE, 
	STATUS EQUIPAMENTO_STATUS DEFAULT 'Ativo',
	PRIMARY KEY (ID)
);